/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminStorageRouteImport } from './routes/_admin.storage'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminPatientsRouteImport } from './routes/_admin.patients'
import { Route as AdminPackagesRouteImport } from './routes/_admin.packages'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminDoctorsRouteImport } from './routes/_admin.doctors'
import { Route as AdminDoctorApprovalRouteImport } from './routes/_admin.doctor-approval'
import { Route as AdminDevicesRouteImport } from './routes/_admin.devices'
import { Route as AdminClinicsRouteImport } from './routes/_admin.clinics'
import { Route as AdminAuditLogRouteImport } from './routes/_admin.audit-log'
import { Route as AdminAiMeasurementsRouteImport } from './routes/_admin.ai-measurements'
import { Route as AdminAdminActionsRouteImport } from './routes/_admin.admin-actions'
import { Route as AdminAccountRouteImport } from './routes/_admin.account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorApprovalRoute = AdminDoctorApprovalRouteImport.update({
  id: '/doctor-approval',
  path: '/doctor-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiMeasurementsRoute = AdminAiMeasurementsRouteImport.update({
  id: '/ai-measurements',
  path: '/ai-measurements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminActionsRoute = AdminAdminActionsRouteImport.update({
  id: '/admin-actions',
  path: '/admin-actions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AdminAccountRoute
  '/admin-actions': typeof AdminAdminActionsRoute
  '/ai-measurements': typeof AdminAiMeasurementsRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/clinics': typeof AdminClinicsRoute
  '/devices': typeof AdminDevicesRoute
  '/doctor-approval': typeof AdminDoctorApprovalRoute
  '/doctors': typeof AdminDoctorsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/packages': typeof AdminPackagesRoute
  '/patients': typeof AdminPatientsRoute
  '/settings': typeof AdminSettingsRoute
  '/storage': typeof AdminStorageRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/account': typeof AdminAccountRoute
  '/admin-actions': typeof AdminAdminActionsRoute
  '/ai-measurements': typeof AdminAiMeasurementsRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/clinics': typeof AdminClinicsRoute
  '/devices': typeof AdminDevicesRoute
  '/doctor-approval': typeof AdminDoctorApprovalRoute
  '/doctors': typeof AdminDoctorsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/packages': typeof AdminPackagesRoute
  '/patients': typeof AdminPatientsRoute
  '/settings': typeof AdminSettingsRoute
  '/storage': typeof AdminStorageRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_admin/account': typeof AdminAccountRoute
  '/_admin/admin-actions': typeof AdminAdminActionsRoute
  '/_admin/ai-measurements': typeof AdminAiMeasurementsRoute
  '/_admin/audit-log': typeof AdminAuditLogRoute
  '/_admin/clinics': typeof AdminClinicsRoute
  '/_admin/devices': typeof AdminDevicesRoute
  '/_admin/doctor-approval': typeof AdminDoctorApprovalRoute
  '/_admin/doctors': typeof AdminDoctorsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/packages': typeof AdminPackagesRoute
  '/_admin/patients': typeof AdminPatientsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/storage': typeof AdminStorageRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/account'
    | '/admin-actions'
    | '/ai-measurements'
    | '/audit-log'
    | '/clinics'
    | '/devices'
    | '/doctor-approval'
    | '/doctors'
    | '/notifications'
    | '/packages'
    | '/patients'
    | '/settings'
    | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/account'
    | '/admin-actions'
    | '/ai-measurements'
    | '/audit-log'
    | '/clinics'
    | '/devices'
    | '/doctor-approval'
    | '/doctors'
    | '/notifications'
    | '/packages'
    | '/patients'
    | '/settings'
    | '/storage'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/forgot-password'
    | '/login'
    | '/_admin/account'
    | '/_admin/admin-actions'
    | '/_admin/ai-measurements'
    | '/_admin/audit-log'
    | '/_admin/clinics'
    | '/_admin/devices'
    | '/_admin/doctor-approval'
    | '/_admin/doctors'
    | '/_admin/notifications'
    | '/_admin/packages'
    | '/_admin/patients'
    | '/_admin/settings'
    | '/_admin/storage'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/storage': {
      id: '/_admin/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/patients': {
      id: '/_admin/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/packages': {
      id: '/_admin/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/doctors': {
      id: '/_admin/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/doctor-approval': {
      id: '/_admin/doctor-approval'
      path: '/doctor-approval'
      fullPath: '/doctor-approval'
      preLoaderRoute: typeof AdminDoctorApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/devices': {
      id: '/_admin/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clinics': {
      id: '/_admin/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-log': {
      id: '/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-measurements': {
      id: '/_admin/ai-measurements'
      path: '/ai-measurements'
      fullPath: '/ai-measurements'
      preLoaderRoute: typeof AdminAiMeasurementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-actions': {
      id: '/_admin/admin-actions'
      path: '/admin-actions'
      fullPath: '/admin-actions'
      preLoaderRoute: typeof AdminAdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/account': {
      id: '/_admin/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAdminActionsRoute: typeof AdminAdminActionsRoute
  AdminAiMeasurementsRoute: typeof AdminAiMeasurementsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminDoctorApprovalRoute: typeof AdminDoctorApprovalRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAdminActionsRoute: AdminAdminActionsRoute,
  AdminAiMeasurementsRoute: AdminAiMeasurementsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminDoctorApprovalRoute: AdminDoctorApprovalRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
